"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Gdbd.py']
APP_NAME = 'Gdbd'
DATA_FILES = ["./default.docx"]
OPTIONS = {'argv_emulation': True, 'iconfile': '/Users/zhanghongtian/PycharmProjects/Gdbd/icon02.icns', 'plist': {
    'CFBundleName': APP_NAME,
    'CFBundleDisplayName': APP_NAME,
    'CFBundleGetInfoString': "GDBD",
    'CFBundleIdentifier': "org.gdbd.app",
    'CFBundleVersion': "0.0.1",
    'CFBundleShortVersionString': "0.0.1",
    'NSHumanReadableCopyright': u"Copyright © 2021, GDBD, All Rights Reserved"
}, 'includes': ['sys', 'logging.handlers.*', 'pony.orm.dbproviders.*', 'docx.templates.*', 'docx.*',
                'docx.shared.*',
                'docx.enum.table.*', 'time',
                'os',
                'wx',
                'logging']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
